name: bertopic-cpu
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy=2.0.0
  - numba=0.60.0
  - pytorch=*=*cpu*
  - pip
  - streamlit
  - sentence-transformers
  - bertopic
  - scikit-learn
  - umap-learn
  - hdbscan
  - pandas
  - plotly
